### ISSUE TITLE
baseband unknown 

### ISSUE THREAD

**Issue by moonlightly** [Flyhalf205/android_device_htc_t6univ#1]
use your source code build cm13 for htc one max sprint and verizon ,after flash baseband unknown

**Comment by BambooIV** [comment]
楼上你这么牛怎么不自己修复？

**Comment by Flyhalf205** [comment]
English dude!

**Comment by shminer** [comment]
月光大神，别删comment啊，我们都是截图的。
按照你的水平，修复这个不是什么难事吧～

**Comment by larryxiao625** [comment]
月亮大神，我们这些小白都在等你的comment修复捏，你的水平修复这个简直就和打苍蝇一样啊(ﾉ≧ڡ≦)

『以上全部是ENGLISH』

The above is not in english... lol

**Comment by xingrz** [comment]
@Flyhalf205 people above are cheering moonlightly up to fix your problem. moonlightly is the most talented developer in out country who maintenance tons of phones 😄

**Comment by shminer** [comment]
@Flyhalf205 The most talented rom-repacker in China.

**Comment by Art-Chen** [comment]
月光大神是我的偶像啊！！！这点小问题都修复不好，对得起你三抽屉的手机不，对得起我们这种小白苦苦等着你的提交么<----------------------- 这段话是English
The above is not in english...

**Comment by larryxiao625** [comment]
@Flyhalf205 The most talented rom-repacker in China  who maintenance tons of phones 😄

**Comment by rong0407** [comment]
围观

**Comment by nian0114** [comment]
围观

**Comment by moetayuko** [comment]
Yep, @moonlightly is the most talented and famous Android developer in China, as you guys see, he has forked device/kernel/vendor of tons of phones on github and always actively maintains them for about a century!
On the other hand, he also has the highest English standards in our country! What an awesome guy he is!

**Comment by gaows20** [comment]
围观

**Comment by vufa** [comment]
围观
